### ISSUE TITLE
SEARCH: Search result is showing the code after refreshing the page

### ISSUE THREAD

**Issue by amateev** [acceptmycrypto/AMC-Web#161]
Search result is showing the code after refreshing the page (see the first img) 
Pages with url containing "/search..." are showing code after refreshing.

MacBook Pro, MacOS, Chrome
<img width="1389" alt="screen shot 2019-01-25 at 12 31 14 pm" src="https://user-images.githubusercontent.com/16661480/51771295-6b14f280-209d-11e9-8779-1b434f11846b.png">

<img width="1389" alt="screen shot 2019-01-25 at 12 29 44 pm" src="https://user-images.githubusercontent.com/16661480/51771163-f641b880-209c-11e9-9272-2496205f22b7.png">

**Comment by simonnguyen3054** [comment]
@Yanananan

**Comment by Yanananan** [comment]
@amateev Please test this again. should be resolved now.  thank you!!

**Comment by amateev** [comment]
@Yanananan Page refreshing is working fine, could you check drop down menu for categories.

**Comment by amateev** [comment]
The issue has been resolved, it can be closed now
