### ISSUE TITLE
Moving stateful components to containers folder

### ISSUE THREAD

**Issue by acceptmycrypto** [acceptmycrypto/AMC-Web#17]
components that got moved
1. Layout
2. Navbar

**Comment by avakrishn** [comment]
@amateev this is ready for testing on development branch.

We're just making sure that the layout and Navbar works and the site still functions properly.

**Comment by acceptmycrypto** [comment]
Interesting. Can you give us the steps here @amateev?

**Comment by amateev** [comment]
git clone url
git checkout remotes/origin/development
add hidden .env
npm install of all packages for backend
nodemon server.js 
in the client folder:
npm install packages
yarn start
test on localhost:3000
login with my credentials
