### ISSUE TITLE
Redux: load user profile

### ISSUE THREAD

**Issue by avakrishn** [acceptmycrypto/AMC-Web#18]
1. Using redux, create userLoad action and user-info reducer that updates the redux store with the user_info, user-crypto, and transactions state when the user profile component loads.

2. Moved stateful UserProfile component to Containers folder.

**Comment by acceptmycrypto** [comment]
@amateev this is ready for testing on development branch. 

We're just making sure that the profile page is still working

**Comment by acceptmycrypto** [comment]
@amateev can you take the screenshot and paste it here please?
