### ISSUE TITLE
Bitcoin Cash address when checkout is displaying incorrectly

### ISSUE THREAD

**Issue by avakrishn** [acceptmycrypto/AMC-Web#190]
I get an address such as "bitcoincash:qqa4rw928glt8h69twnsvnjwfa8zmguq8gdege99np"
The address shouldn't have "bitcoincash" prepended to the address and the QR code does not contain the wallet address but just contains "bitcoin cash" as its data.

**Comment by simonnguyen3054** [comment]
@avanika So bitcoin cash hard forked last month and now it’s address is
prepended with bitcoincash

**Comment by avakrishn** [comment]
good to know. I am closing this issue.
