### ISSUE TITLE
Code is shown on 'Books/Audible', 'Electronics/Computers/Office' and 'Sport/Outdoors' category pages.

### ISSUE THREAD

**Issue by amateev** [acceptmycrypto/AMC-Web#211]
Code is shown on 'Books/Audible', 'Electronics/Computers/Office' and 'Sport/Outdoors' category pages.

<img width="1372" alt="code in deals 2019-02-21 at 9 19 53 pm" src="https://user-images.githubusercontent.com/16661480/53707653-b29d4580-3de4-11e9-87b0-0f1edd913713.png">

**Comment by simonnguyen3054** [comment]
@amateev This is fixed as well. Please double check. Thanks
