### ISSUE TITLE
When creating a deal with two or more categories, the list of categories is displayed multiple times on the deal page. 'Buy Now' button does not have enough padding.

### ISSUE THREAD

**Issue by amateev** [acceptmycrypto/AMC-Web#212]
#1. When creating a deal with two or more categories, the list of categories is displayed multiple times on the deal page.
leads to an issue #2: Not enough padding for 'Buy Now' button.

<img width="1665" alt="category bug for create deal 2019-02-22 at 3 46 45 pm" src="https://user-images.githubusercontent.com/16661480/53708011-3efc3800-3de6-11e9-80b6-8a54c673a703.png">
<img width="1639" alt="no padding for a button on deal page 2019-02-22 at 3 48 29 pm" src="https://user-images.githubusercontent.com/16661480/53708030-5c310680-3de6-11e9-825c-8653c3cb9b77.png">

**Comment by simonnguyen3054** [comment]
@amateev This is fixed. Can you test again?
