### ISSUE TITLE
Limit the deal name to two lines on mobile view 

### ISSUE THREAD

**Issue by simonnguyen3054** [acceptmycrypto/AMC-Web#239]
![Image from iOS (10)](https://user-images.githubusercontent.com/33471438/54234736-ee16ce80-44cc-11e9-803d-d30a8d002f42.png)

If the name of the deal is long, we need to truncate and add ...

**Comment by avakrishn** [comment]
@amateev This is ready for testing.

**Comment by amateev** [comment]
This issue can be closed
